name: Deploy ke AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/${{ secrets.EC2_USERNAME }}
          # Clone repo jika belum ada, atau update jika sudah ada
          if [ ! -d "uts-cloud-diabetes" ]; then
            git clone https://github.com/nafa13/uts-cloud-diabetes.git
          fi
          cd uts-cloud-diabetes
          git pull origin main
          
          # Hapus aplikasi lama yang mungkin masih jalan
          sudo docker stop web-diabetes || true
          sudo docker rm web-diabetes || true
          
          # Build Docker baru
          sudo docker build -t app-diabetes .
          
          # Jalankan Docker dengan SEMUA variabel RDS dan S3
          sudo docker run -d -p 5000:5000 \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=ap-southeast-1 \
            -e S3_BUCKET_NAME=bucket-diabetes-nafal \
            --name web-diabetes app-diabetes